databases: []

services:
  - type: web
    name: dawah-merch
    runtime: ruby
    plan: starter
    buildCommand: ./bin/bundle install && ./bin/rails assets:precompile && ./bin/rails assets:clean
    startCommand: ./bin/rails server
    healthCheckPath: /up
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: BASE_URL
        value: https://dawah-merch.onrender.com
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: LITESTACK_DATA_PATH
        value: /data
      - key: ACTIVE_STORAGE_PATH
        value: /data/storage
