default: &default
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    adapter: turso
    database: <%= ENV["TURSO_DATABASE_URL"] %>
    token: <%= ENV["TURSO_AUTH_TOKEN"] %>
  cache:
    <<: *default
    adapter: turso
    database: <%= ENV["TURSO_DATABASE_URL"] %>
    token: <%= ENV["TURSO_AUTH_TOKEN"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    adapter: turso
    database: <%= ENV["TURSO_DATABASE_URL"] %>
    token: <%= ENV["TURSO_AUTH_TOKEN"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    adapter: turso
    database: <%= ENV["TURSO_DATABASE_URL"] %>
    token: <%= ENV["TURSO_AUTH_TOKEN"] %>
    migrations_paths: db/cable_migrate
